name: Docker Image CI

on:
  push:
    branches: [ "qt-5.12.5" ]
  pull_request:
    branches: [ "qt-5.12.5" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qt-builder:$(date +%s)

